### ISSUE TITLE
Database creation

### ISSUE THREAD

**Issue by hritika00** [Abishekneupane/Project#1]
Users would have to create the databases and tables on their own right now. Implement the code so that the databases and tables are automatically created.

**Comment by Satkar30** [comment]
Can you please elaborate this.

**Comment by hritika00** [comment]
Sure, write the code to automate the process so that our project has a consistent and predictable database schema, and that users don’t need to manually create the database and tables themselves. This can save time and reduce the risk of errors or inconsistencies in the database schema.

**Comment by Satkar30** [comment]
Sure, will work on it.

**Comment by Abishekneupane** [comment]
Here client should have to add his/her database name instead of Taxman(i.e developer database name) and the table are automatically created in his/her database.

**Comment by ashikasherpa5** [comment]
Sure we will work on the given issue
